name: tag-release-branch-updates

on:
  push:
    branches:
      - 'releases/**'
env:
  NODE_VERSION: '15'
  PYTHON_VERSOIN: '2.7.18'
  DOTNET_VERSION: '6.x'

jobs:
  # build the project
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:

      # ============ TAG BRANCH ===============

      # Create Tag
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''